### ISSUE TITLE
Connecting via TLS not supported

### ISSUE THREAD

**Issue by m1foley** [hedwig-im/hedwig_xmpp#1]
Is it possible to connect to XMPP via TLS? Hedwig v0.1.0 used to have the `require_tls?` option in `config.exs` ([ikbot](https://github.com/inaka/ikbot/blob/master/config/config.exs.template) is one example of a bot that still uses that). It no longer appears that this is supported.

**Comment by scrogson** [comment]
@m1foley This will be handled in https://github.com/scrogson/romeo.

Hedwig never supported that properly even though I have always had the option `require_tls?` 😉 

I have an open issue here: https://github.com/scrogson/romeo/issues/2
